#version 450

layout (binding = 0, rg32ui) uniform readonly uimage2D visibility_buffer;

layout (std430, binding = 1) readonly buffer InstanceData {
    vec4 instance_datas[];
};

layout (std430, binding = 2) writeonly buffer ResultBuffer {
    uint result;
};

layout (push_constant) uniform Constants {
    uvec2 pos;
};

// 根据 VisibilityBuffer 拾取像素位置上的 MeshInstance 索引
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main() {
    uvec2 info = imageLoad(visibility_buffer, ivec2(pos)).xy;
    if (info.x + info.y == 0) {
        result = uint(-1);
        return;
    }
    result = uint(instance_datas[info.x * 9].w);
}
